### ISSUE TITLE
Can not compile with typescript

### ISSUE THREAD

**Issue by chemzqm** [neovim/node-client#57]
```
~/vim-dev/complete.nvim(master|●7✚3…)
❯ npm run build

> complete.nvim@0.0.1 build /Users/chemzqm/vim-dev/complete.nvim
> tsc

src/index.ts(3,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Cannot invoke an expression whose type lacks a call signature. Type 'PluginWrapperConstructor | ((cls: any) => PluginWrapperConstructor)' has no compatible call signatures.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! complete.nvim@0.0.1 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the complete.nvim@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chemzqm/.npm/_logs/2018-05-02T23_33_30_165Z-debug.log
```
Change
```
export declare function plugin(outter: any): PluginWrapperConstructor | ((cls: any) => PluginWrapperConstructor);
```
to
```
export declare function plugin(outter: any): any
```
 in `neovim/lib/plugin/plugin.d.ts` could fix this problem, I don't know if there is better way.

**Comment by rhysd** [comment]
I think this is already fixed in the current master branch because the `any` return type signature is defined in master, but not in the latest release 3.5.2.

https://github.com/neovim/node-client/blob/849f408a100b42091c160f0125812ca3172ee573/src/plugin/plugin.ts

@billyvg Is it ok to release new version? I think #54 should be released.

**Comment by chemzqm** [comment]
@rhysd Probably no, I'm using master branch
```
> tsc

src/index.ts(19,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Cannot invoke an expression whose type lacks a call signature. Type 'PluginWrapperConstructor | ((cls: any) => PluginWrapperConstructor)' has no compatible call signatures.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! complete.nvim@0.0.1 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the complete.nvim@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chemzqm/.npm/_logs/2018-05-07T08_34_33_761Z-debug.log
```

**Comment by billyvg** [comment]
@rhysd Yeah I wanted to do a few more manual tests before cutting a release -- I'll publish a release this weekend.

**Comment by rhysd** [comment]
@chemzqm 

Oh, you're already trying HEAD, right? I think we need to investigate more. I think reproducing the issue is the first step.

@billyvg 

Thank you. I think this compile error issue should be solved before release.

**Comment by chemzqm** [comment]
@rhysd find out I was using an outdated master version.

**Comment by chemzqm** [comment]
@rhysd Still can't actually. 
I've created a sample project: https://github.com/chemzqm/node-client-sample
But the compile get another issue:
```
> node-client-sample@0.0.1 build /Users/chemzqm/nodejs-dev/node-client-sample
> tsc

src/index.ts(3,2): error TS2345: Argument of type 'typeof CompletePlugin' is not assignable to parameter of type 'PluginWrapperConstructor'.
  Type 'CompletePlugin' is not assignable to type 'PluginWrapperInterface'.
    Property 'setApi' is missing in type 'CompletePlugin'.
npm ERR! code ELIFECYCLE
```
